In [1]:
import sqlite3
import pandas as pd
import json

DB_PATH = "db.sqlite"

conn = sqlite3.connect(DB_PATH)

# Show all tables
tables = pd.read_sql_query("""
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
""", conn)

display(tables)

              name
0     participants
1   phase_sessions
2  sqlite_sequence
3       trial_data

In [2]:
pd.read_sql_query(
    """
    SELECT *
    FROM phase_sessions
    WHERE prolific_id = 'resume_test001'
    """,
    conn
)

,id,prolific_id,phase,trial_order,created_at,updated_at
0,1,resume_test001,phase1,"[""test|asphalt|d|null|testing|ratings"", ""test|...",2026-09-18 12:47:10,2026-09-18 12:47:10

In [3]:
participants = pd.read_sql_query(
    """
    SELECT *
    FROM participants
    ORDER BY created_at
    """,
    conn
)

display(participants)

        prolific_id           created_at         last_seen_at
0           test001  2026-09-18 11:51:03  2026-09-18 11:52:00
1    resume_test001  2026-09-18 12:47:10  2026-09-18 14:18:33
2    resume_test002  2026-09-18 12:59:37  2026-09-18 14:17:39
3    resume_test003  2026-09-18 14:19:23  2026-09-18 14:20:03
4   resume_test0034  2026-09-18 14:21:19  2026-09-21 10:00:42
5         newIDtest  2026-09-21 10:40:07  2026-09-21 16:11:42
6              None  2026-09-22 20:46:33  2026-09-23 08:21:37
7    fresh_test_001  2026-09-23 08:26:39  2026-09-23 09:40:42
8    fresh_test_002  2026-09-23 09:40:49  2026-09-23 10:27:39
9    fresh_test_003  2026-09-23 10:28:28  2026-09-23 10:33:13
10   fresh_test_004  2026-09-23 11:05:59  2026-09-23 11:07:07

In [4]:
trials = pd.read_sql_query(
    """
    SELECT *
    FROM trial_data
    ORDER BY id
    """,
    conn
)

display(trials)

,id,prolific_id,phase,trial_key,trial_index,section,sound_id,training,payload,created_at
0,1,test001,phase1,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 11:51:03
1,2,test001,phase1,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 11:51:34
2,3,test001,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 11:51:48
3,4,test001,phase1,test|hay_1|d|2.9322|testing|ratings,NaN,test,hay_1,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""ha...",2026-09-18 11:52:00
4,5,resume_test001,phase1,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 12:57:08
5,6,resume_test001,phase1,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 12:57:16
6,7,resume_test001,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 12:57:39
7,8,resume_test001,phase1,test|asphalt|d|null|testing|ratings,NaN,test,asphalt,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""as...",2026-09-18 12:57:54
8,9,resume_test001,phase1,test|sneakers_gravel|f|null|baseline|ratings,NaN,test,sneakers_gravel,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""sn...",2026-09-18 12:58:05
9,10,resume_test001,phase1,test|asphalt|d|6.99845|testing|ratings,NaN,test,asphalt,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""as...",2026-09-18 12:58:30
10,11,resume_test001,phase1,test|dress_shoes_2|d|null|testing|ratings,NaN,test,dress_shoes_2,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""dr...",2026-09-18 12:58:51
11,12,resume_test002,phase1,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 12:59:57
12,13,resume_test002,phase1,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 13:00:05
13,14,resume_test002,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 13:00:19
14,15,resume_test001,phase1,test|gravel|f|null|testing|ratings,NaN,test,gravel,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 14:17:17
15,16,resume_test001,phase1,test|leaving_walk|d|1.78242|testing|ratings,NaN,test,leaving_walk,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""le...",2026-09-18 14:17:28
16,17,resume_test001,phase1,test|hallway_walk|d|null|testing|ratings,NaN,test,hallway_walk,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""ha...",2026-09-18 14:18:22
17,18,resume_test003,phase1,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 14:19:33
18,19,resume_test003,phase1,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 14:19:40
19,20,resume_test003,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 14:19:54
20,21,resume_test0034,phase1,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 14:22:15
21,22,resume_test0034,phase1,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 14:25:47
22,23,resume_test0034,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""gr...",2026-09-18 14:26:09
23,24,resume_test0034,phase1,test|hay_2|f|2.9322|testing|ratings,NaN,test,hay_2,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""ha...",2026-09-18 14:26:39
24,25,resume_test0034,phase1,test|sneakers_gravel|f|null|baseline|ratings,NaN,test,sneakers_gravel,0,"{""step"": ""ratings"", ""phase"": 1, ""soundId"": ""sn...",2026-09-18 14:26:50
25,26,resume_test0034,phase2,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 14:33:53
26,27,resume_test0034,phase2,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 14:36:35
27,28,resume_test0034,phase2,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,"{""step"": ""ratings"", ""phase"": 2, ""soundId"": ""gr...",2026-09-18 14:37:23
28,29,resume_test0034,phase2,training|wood|d|null|testing|ratings,NaN,training,wood,1,"{""step"": ""ratings"", ""phase"": 2, ""soundId"": ""wo...",2026-09-18 14:37:59
29,30,resume_test0034,phase2,training|asphalt|d|null|testing|ratings,NaN,training,asphalt,1,"{""step"": ""ratings"", ""phase"": 2, ""soundId"": ""as...",2026-09-18 14:38:18
30,31,resume_test0034,phase2,training|heels_concrete|d|null|testing|ratings,NaN,training,heels_concrete,1,"{""step"": ""ratings"", ""phase"": 2, ""soundId"": ""he...",2026-09-18 14:38:33
31,32,resume_test0034,phase2,test|gravel|f|0.499127|testing|ratings,NaN,test,gravel,0,"{""step"": ""ratings"", ""phase"": 2, ""soundId"": ""gr...",2026-09-18 14:38:48
32,33,resume_test0034,phase3,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-18 14:40:15
33,34,resume_test0034,phase3,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-18 14:40:24
34,35,newIDtest,phase3,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-21 10:40:17
35,36,newIDtest,phase3,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-21 10:40:24
36,37,newIDtest,phase3,training|0|ratings,0.0,training,None,1,"{""step"": ""ratings"", ""phase"": 3, ""trialIndex"": ...",2026-09-21 10:40:52
37,38,newIDtest,phase3,test|0|ratings,0.0,test,None,0,"{""step"": ""ratings"", ""phase"": 3, ""trialIndex"": ...",2026-09-21 10:41:59
38,39,fresh_test_001,phase2,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-23 09:27:49
39,40,fresh_test_001,phase2,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-23 09:27:57
40,41,fresh_test_001,phase2,test|0|ratings,0.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 09:28:34
41,42,fresh_test_001,phase2,test|1|ratings,1.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 09:28:55
42,43,fresh_test_001,phase2,test|2|ratings,2.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 09:29:10
43,44,fresh_test_002,phase2,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-23 09:40:59
44,45,fresh_test_002,phase2,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-23 09:41:06
45,46,fresh_test_002,phase2,test|0|ratings,0.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 09:41:23
46,47,fresh_test_002,phase2,catch|development,1.0,catch,None,0,"{""step"": ""catch"", ""catchId"": ""animal_meow"", ""c...",2026-09-23 09:41:28
47,48,fresh_test_003,phase2,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-23 10:28:52
48,49,fresh_test_003,phase2,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-23 10:29:03
49,50,fresh_test_003,phase2,training|0|ratings,0.0,training,None,1,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:29:38
50,51,fresh_test_003,phase2,training|1|ratings,1.0,training,None,1,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:30:07
51,52,fresh_test_003,phase2,training|2|ratings,2.0,training,None,1,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:30:35
52,53,fresh_test_003,phase2,test|0|ratings,0.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:31:02
53,54,fresh_test_003,phase2,catch|development,1.0,catch,None,0,"{""step"": ""catch"", ""catchId"": ""animal_meow"", ""c...",2026-09-23 10:31:08
54,55,fresh_test_003,phase2,test|1|ratings,1.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:31:37
55,56,fresh_test_003,phase2,test|2|ratings,2.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:31:56
56,57,fresh_test_003,phase2,test|3|ratings,3.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:32:14
57,58,fresh_test_003,phase2,test|4|ratings,4.0,test,None,0,"{""step"": ""ratings"", ""phase"": 2, ""participantId...",2026-09-23 10:32:39
58,59,fresh_test_004,phase2,calibration|volume,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""v...",2026-09-23 11:06:44
59,60,fresh_test_004,phase2,calibration|stereo,NaN,calibration,None,0,"{""step"": ""calibration"", ""calibration_test"": ""s...",2026-09-23 11:07:07

In [5]:
trials = pd.read_sql_query(
    """
    SELECT *
    FROM trial_data
    ORDER BY id
    """,
    conn
)

if len(trials) > 0:
    payload = trials["payload"].apply(json.loads)
    payload_df = pd.json_normalize(payload)

    results = pd.concat(
        [
            trials.drop(columns=["payload"]).reset_index(drop=True),
            payload_df.reset_index(drop=True)
        ],
        axis=1
    )

    display(results)
else:
    print("No trials saved yet.")

,id,prolific_id,phase,trial_key,trial_index,section,sound_id,training,created_at,step,...,editedPath,soundAType,soundBType,catchId,catchIndex,afterPair,correctAnswer,developmentTest,selectedAnswer,acceptable_volume
0,1,test001,phase1,calibration|volume,NaN,calibration,None,0,2026-09-18 11:51:03,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,test001,phase1,calibration|stereo,NaN,calibration,None,0,2026-09-18 11:51:34,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,test001,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 11:51:48,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,test001,phase1,test|hay_1|d|2.9322|testing|ratings,NaN,test,hay_1,0,2026-09-18 11:52:00,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,resume_test001,phase1,calibration|volume,NaN,calibration,None,0,2026-09-18 12:57:08,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,resume_test001,phase1,calibration|stereo,NaN,calibration,None,0,2026-09-18 12:57:16,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,resume_test001,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 12:57:39,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,resume_test001,phase1,test|asphalt|d|null|testing|ratings,NaN,test,asphalt,0,2026-09-18 12:57:54,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,resume_test001,phase1,test|sneakers_gravel|f|null|baseline|ratings,NaN,test,sneakers_gravel,0,2026-09-18 12:58:05,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,resume_test001,phase1,test|asphalt|d|6.99845|testing|ratings,NaN,test,asphalt,0,2026-09-18 12:58:30,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,resume_test001,phase1,test|dress_shoes_2|d|null|testing|ratings,NaN,test,dress_shoes_2,0,2026-09-18 12:58:51,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,resume_test002,phase1,calibration|volume,NaN,calibration,None,0,2026-09-18 12:59:57,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,resume_test002,phase1,calibration|stereo,NaN,calibration,None,0,2026-09-18 13:00:05,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,resume_test002,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 13:00:19,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,resume_test001,phase1,test|gravel|f|null|testing|ratings,NaN,test,gravel,0,2026-09-18 14:17:17,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,resume_test001,phase1,test|leaving_walk|d|1.78242|testing|ratings,NaN,test,leaving_walk,0,2026-09-18 14:17:28,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,resume_test001,phase1,test|hallway_walk|d|null|testing|ratings,NaN,test,hallway_walk,0,2026-09-18 14:18:22,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,resume_test003,phase1,calibration|volume,NaN,calibration,None,0,2026-09-18 14:19:33,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,resume_test003,phase1,calibration|stereo,NaN,calibration,None,0,2026-09-18 14:19:40,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,resume_test003,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 14:19:54,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,resume_test0034,phase1,calibration|volume,NaN,calibration,None,0,2026-09-18 14:22:15,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,resume_test0034,phase1,calibration|stereo,NaN,calibration,None,0,2026-09-18 14:25:47,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,resume_test0034,phase1,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 14:26:09,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,resume_test0034,phase1,test|hay_2|f|2.9322|testing|ratings,NaN,test,hay_2,0,2026-09-18 14:26:39,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,resume_test0034,phase1,test|sneakers_gravel|f|null|baseline|ratings,NaN,test,sneakers_gravel,0,2026-09-18 14:26:50,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,resume_test0034,phase2,calibration|volume,NaN,calibration,None,0,2026-09-18 14:33:53,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,resume_test0034,phase2,calibration|stereo,NaN,calibration,None,0,2026-09-18 14:36:35,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,resume_test0034,phase2,training|gravel|d|null|testing|ratings,NaN,training,gravel,1,2026-09-18 14:37:23,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,resume_test0034,phase2,training|wood|d|null|testing|ratings,NaN,training,wood,1,2026-09-18 14:37:59,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,resume_test0034,phase2,training|asphalt|d|null|testing|ratings,NaN,training,asphalt,1,2026-09-18 14:38:18,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,resume_test0034,phase2,training|heels_concrete|d|null|testing|ratings,NaN,training,heels_concrete,1,2026-09-18 14:38:33,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,resume_test0034,phase2,test|gravel|f|0.499127|testing|ratings,NaN,test,gravel,0,2026-09-18 14:38:48,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,resume_test0034,phase3,calibration|volume,NaN,calibration,None,0,2026-09-18 14:40:15,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,resume_test0034,phase3,calibration|stereo,NaN,calibration,None,0,2026-09-18 14:40:24,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,newIDtest,phase3,calibration|volume,NaN,calibration,None,0,2026-09-21 10:40:17,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,newIDtest,phase3,calibration|stereo,NaN,calibration,None,0,2026-09-21 10:40:24,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,newIDtest,phase3,training|0|ratings,0.0,training,None,1,2026-09-21 10:40:52,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,newIDtest,phase3,test|0|ratings,0.0,test,None,0,2026-09-21 10:41:59,ratings,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,fresh_test_001,phase2,calibration|volume,NaN,calibration,None,0,2026-09-23 09:27:49,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,fresh_test_001,phase2,calibration|stereo,NaN,calibration,None,0,2026-09-23 09:27:57,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,fresh_test_001,phase2,test|0|ratings,0.0,test,None,0,2026-09-23 09:28:34,ratings,...,/static/stimulis/stimulis_first_half/test_yt_s...,original,edited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,fresh_test_001,phase2,test|1|ratings,1.0,test,None,0,2026-09-23 09:28:55,ratings,...,/static/stimulis/stimulis_first_half/test_plug...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,fresh_test_001,phase2,test|2|ratings,2.0,test,None,0,2026-09-23 09:29:10,ratings,...,/static/stimulis/stimulis_second_half/test_yt_...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,fresh_test_002,phase2,calibration|volume,NaN,calibration,None,0,2026-09-23 09:40:59,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,fresh_test_002,phase2,calibration|stereo,NaN,calibration,None,0,2026-09-23 09:41:06,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,fresh_test_002,phase2,test|0|ratings,0.0,test,None,0,2026-09-23 09:41:23,ratings,...,/static/stimulis/stimulis_first_half/test_yt_s...,original,edited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,fresh_test_002,phase2,catch|development,1.0,catch,None,0,2026-09-23 09:41:28,catch,...,NaN,NaN,NaN,animal_meow,development,1.0,Cat,True,Cat,NaN
47,48,fresh_test_003,phase2,calibration|volume,NaN,calibration,None,0,2026-09-23 10:28:52,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,49,fresh_test_003,phase2,calibration|stereo,NaN,calibration,None,0,2026-09-23 10:29:03,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,50,fresh_test_003,phase2,training|0|ratings,0.0,training,None,1,2026-09-23 10:29:38,ratings,...,None,training,training,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,51,fresh_test_003,phase2,training|1|ratings,1.0,training,None,1,2026-09-23 10:30:07,ratings,...,None,training,training,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,52,fresh_test_003,phase2,training|2|ratings,2.0,training,None,1,2026-09-23 10:30:35,ratings,...,None,training,training,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,53,fresh_test_003,phase2,test|0|ratings,0.0,test,None,0,2026-09-23 10:31:02,ratings,...,/static/stimulis/stimulis_first_half/test_yt_s...,original,edited,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,54,fresh_test_003,phase2,catch|development,1.0,catch,None,0,2026-09-23 10:31:08,catch,...,NaN,NaN,NaN,animal_meow,development,1.0,Cat,True,Cat,NaN
54,55,fresh_test_003,phase2,test|1|ratings,1.0,test,None,0,2026-09-23 10:31:37,ratings,...,/static/stimulis/stimulis_first_half/test_plug...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,56,fresh_test_003,phase2,test|2|ratings,2.0,test,None,0,2026-09-23 10:31:56,ratings,...,/static/stimulis/stimulis_second_half/test_yt_...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,57,fresh_test_003,phase2,test|3|ratings,3.0,test,None,0,2026-09-23 10:32:14,ratings,...,/static/stimulis/stimulis_first_half/Turchet_b...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,58,fresh_test_003,phase2,test|4|ratings,4.0,test,None,0,2026-09-23 10:32:39,ratings,...,/static/stimulis/stimulis_second_half/test_plu...,edited,original,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,59,fresh_test_004,phase2,calibration|volume,NaN,calibration,None,0,2026-09-23 11:06:44,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
59,60,fresh_test_004,phase2,calibration|stereo,NaN,calibration,None,0,2026-09-23 11:07:07,calibration,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN